name: mall
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  persistent_bottom_nav_bar_v2: ^5.2.0
  auto_size_text:
  flutter_colorpicker: ^1.0.3
  flutter_animate: ^4.5.0
  flutter_slidable: ^3.1.0

  # BLOC
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.28.0

  # Custom Repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/