// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK19K6j6nPm4ITuK6eHqzxhR1Qgd6Ite8',
    appId: '1:1056136077133:web:9b1ce7b13ba68ddb5a6104',
    messagingSenderId: '1056136077133',
    projectId: 'good-food-a7f51',
    authDomain: 'good-food-a7f51.firebaseapp.com',
    databaseURL: 'https://good-food-a7f51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'good-food-a7f51.appspot.com',
    measurementId: 'G-SCCP31SYBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZEdoMJcXyyOiVnUhs73vyITTkg0AwYQ',
    appId: '1:1056136077133:android:f2532d83d9d2352d5a6104',
    messagingSenderId: '1056136077133',
    projectId: 'good-food-a7f51',
    databaseURL: 'https://good-food-a7f51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'good-food-a7f51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEJQGJ6MgrO8PlfKXpahpv4E_QVw78Kg',
    appId: '1:1056136077133:ios:19460c62c43899165a6104',
    messagingSenderId: '1056136077133',
    projectId: 'good-food-a7f51',
    databaseURL: 'https://good-food-a7f51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'good-food-a7f51.appspot.com',
    iosBundleId: 'com.example.mall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtEJQGJ6MgrO8PlfKXpahpv4E_QVw78Kg',
    appId: '1:1056136077133:ios:3068959cc7028b265a6104',
    messagingSenderId: '1056136077133',
    projectId: 'good-food-a7f51',
    databaseURL: 'https://good-food-a7f51-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'good-food-a7f51.appspot.com',
    iosBundleId: 'com.example.mall.RunnerTests',
  );
}
